name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test
    
    - name: Run gocyclo
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u github.com/fzipp/gocyclo
        make gocyclo_all
